### PR TITLE
Updated Spanish language

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**
Removed Tesselation options strings and added Kronos SH2 interpreter and ST-V options.

### CODE REVIEW

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo 
Sorry, but why Tesselation options has been removed?
I noticed too that other options such as "Use integer pixel scaling" Window resolution" "Time Synchronization Mode" or "Fullscreen resolution" has been removed between Kronos and the Yaba Sanshiro ¿?

**Comment by BenjaminSiskoo** [comment]
@luismaSP89 Hello, removing an option is not necessarily a regression. François checked this option and he didn't see how usefull is ? Maybe you have an exemple ?

**Comment by LuismaSP89** [comment]
Hi, first of all, thanks for your reply.

I don't know which option of these is, but indeed these options have a great improvement in 3D graphics, I opened an issue here:

https://github.com/FCare/Kronos/issues/181

As you can see, 3D rendering is greatly improved in Yaba Sanshiro, and Kronos have artifacts in the 3d objects. I tried with default settings, and changing all settings, but none can compare with the Yaba ones, then, some of that removed options must be useful for some reason.

**Comment by LuismaSP89** [comment]
@BenjaminSiskoo Sorry, I forgot to include "@BenjaminSiskoo" in my previous reply. And I don´t know if it´s necessary to send you the answer.

**Comment by BenjaminSiskoo** [comment]
@LuismaSP89 No problem I've got notifications.

**Pull request merged**
