### PR TITLE
Updated brazilian portuguese's translation

### PR DESCRIPTION
**Pull request by Felipefpl**
Kronos uses my translation to yabause, i updated/fixed it. This being said there are things i need to ask/report:

1 - why are there 2 translation files in the repository?

2 - this phrase doesnt exist in the emulator: "Native (native resolution of Window)", instead it uses "Native (current resolution of Window)" because of this i believe the phrase isnt translated.

3 - there are several phrases still untranslated in the emulator.

4 - this phrase isnt shown in the about box: "Kronos Qt Gui<br />Based on Yabause %1<br /><a href="http://yabause.org">http://yabause.org</a><br />The Yabause Team<br /><a href="mailto:pasnox@gmail.com">Filipe AZEVEDO</a>"

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
Hi, 

1) I don't know.
2) and 3) Updated file are french, spanish, deutsch and russian. All strings are there. Others languages are outdated. Some strings are not translated because it's not possible for now. Language system need a refactoring, but it's not for now. There are lots of things to do before.
4) Kronos is based on UoYabause/Yaba Sanshiro, not from Yabause. So Maybe these strings was removed at this time.

**Comment by Felipefpl** [comment]
Hi Siskoo, thanks for the answers, drop by on #yabause on irc.libera.chat once in a while, you have been missed. ;)

**Comment by vbt1** [comment]
> Hi Siskoo, thanks for the answers, drop by on #yabause on irc.libera.chat once in a while, you have been missed. ;)

thanks felipe !!!!

**Comment by BenjaminSiskoo** [comment]
> Hi Siskoo, thanks for the answers, drop by on #yabause on irc.libera.chat once in a while, you have been missed. ;)

Hello, No one remembers of me on the irc. Cyby is leaving, there is just you :)

**Comment by Felipefpl** [comment]
> thanks felipe !!!!

hi vbt, thanks for what?? O_O

> Hello, No one remembers of me on the irc. Cyby is leaving, there is just you :)

I doubt no one remembers you, you should go there. ;)

Btw, only Kronos's author can submit my translation?

**Comment by Felipefpl** [comment]
Fcare - Thanks for the submission. :)

**Pull request merged**
