### PR TITLE
System language change functionality

### PR DESCRIPTION
**Pull request by Will-LWE**
Hello,

I offer this small contribution to allow changing the system language from the bios settings which is always in English after each start of the emulation.

With this modification, it is now possible to change the language from the "-l" or "--language" command line, then the option can also be modified from the application settings and then saved in the configuration file.

Some games, like Rayman for example, do not allow you to select the language and are based on the language configuration from the system settings. This can be annoying if a player wants to play their game in their native language or of their choice.

Test performed on Linux. The code must be good for Windows also.

Hoping that this contribution can interest you because it brings a comfort during the game to the player.

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
Thanks for your commit :) 

François is really busy for now. So it should take some time before a possible merge. Do not quiet :)

**Comment by Will-LWE** [comment]
OK, no problem. You are welcome.
Thank you.

**Comment by BenjaminSiskoo** [comment]
@Will-LWE it's seems you made some fixes on yaba, would you mind to add them too.

Edit : I made a quick test with rayman, and it works properly, nice add :)

**Comment by barbudreadmon** [comment]
c'est toujours marrant de voir un groupe de français se parler en anglais entre eux xD

**Pull request merged**
