### PR TITLE
Fcare cmake libretro

### PR DESCRIPTION
**Pull request by rob-ack**
this changes the cmake project system with the goal of libretro core builds more general purpose setups for compilers and debug settings. it fixes some issues with cross compilation on platforms.

see commit messages for more details.
 
(since its a rebase this is draft and will be tested before opened for merge. also the corresponding c code for some features like define usages are missing in this PR due to the rebase process and to keep them more separated from this commit)

### CODE REVIEW

**Comment by barbudreadmon** [comment]
I'm kinda lost by this PR. FYI the current libretro port isn't building the content of `yabause/src/tools/gllibs`, it's using libretro's glsym as a replacement. Except if there is some kind of major issue i'm unaware of about that, i want to keep it that way.

**Comment by rob-ack** [comment]
> I'm kinda lost by this PR. FYI the current libretro port isn't building the content of `yabause/src/tools/gllibs`, it's using libretro's glsym as a replacement. Except if there is some kind of major issue i'm unaware of about that, i want to keep it that way.

Feel free to comment on lines you want Infos about. 
Since we discussed recently on rd that Linux is not a target we may change/remove the scripts and files around glext. Most files which got added are about the various dependencies different configurations have.

**Comment by barbudreadmon** [comment]
Well, this isn't about a line, this is about the dozen of files from gllibs being updated in this PR, while gllibs mustn't be built into the libretro port.

**Comment by rob-ack** [comment]
> Well, this isn't about a line, this is about the dozen of files from gllibs being updated in this PR, while gllibs mustn't be built into the libretro port.

yes i understand. those are not updated but added so they can be consumed when needed.
i have build various configurations and those where definitely not found during builds. probably i was also building obsolete configurations or ports (like linux) which are not required anymore. i already asked about what's required. in fact i even think that the semaphore class is not necessarily needed but its required when building with msvc windows and async sh2 switch turned on. 
so removing the gllib headers from the pr can be done (sacrificing some build configurations/paths which should be cleaned up anyways. and the linux port is obsolete and has compile issues anyways)

**Comment by FCare** [comment]
@rob-ack Can you please make a PR withthis simple patch?
https://github.com/rob-ack/yabause/commit/a1a127a0b4aeefcf435f5a92b5ef0410f95ac9d0
That way, you will get the kudos.

I think other patches will be refuse since libretro is handle by @barbudreadmon and I am not sure they are needed.

for sure, the soft renderer is not maintained on Kronos. It has no real sens. It consume so much CPU that the user will prefer mednafen then.

The code is still there just due to debug screen. There is a ToDo to move this debug on openGL renderer. But that is one of the numerous ToDo :-)

**Comment by rob-ack** [comment]
> @rob-ack Can you please make a PR withthis simple patch?
> [rob-ack@a1a127a](https://github.com/rob-ack/yabause/commit/a1a127a0b4aeefcf435f5a92b5ef0410f95ac9d0)
> That way, you will get the kudos.

here you go #1137

**Pull request closed without merging**
